### ISSUE TITLE
Zalomovani radku

### ISSUE THREAD

**Issue by mandik-spsejecna-cz** [skola-ukoly/wa_chat#1]
Na chatu nejde odeslat zprava co ma dva a vice radku, slo by to vyresit. Treba textarea?

**Comment by OndrejHana** [comment]
Dekuji za navrh, vyzkousim implementaci na feature branch

**Comment by OndrejHana** [comment]
#[2e767d9](https://github.com/skola-ukoly/wa_chat/commit/2e767d9a314f603a83ebda0179a654127baaee5f)

**Comment by OndrejHana** [comment]
#dbd7a9105430f6f5345a0ef79ac1f91cf0b71c29
